// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6RbCstC2ZxcOrit6qOSvY4g7PuMkOojQ',
    appId: '1:1062632767636:web:a7845e56e9483f2b5db481',
    messagingSenderId: '1062632767636',
    projectId: 'ecommerce-app-ba189',
    authDomain: 'ecommerce-app-ba189.firebaseapp.com',
    storageBucket: 'ecommerce-app-ba189.appspot.com',
    measurementId: 'G-M7JKYDG9YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLlJaz4Wlp6cQh_Pa0Tg5albwWohpiKk',
    appId: '1:1062632767636:android:db0897e1b682b99a5db481',
    messagingSenderId: '1062632767636',
    projectId: 'ecommerce-app-ba189',
    storageBucket: 'ecommerce-app-ba189.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVi9Ctv_tzmrcQLpF8arjMNTYxQOD6Vwk',
    appId: '1:1062632767636:ios:98880222830bcfd35db481',
    messagingSenderId: '1062632767636',
    projectId: 'ecommerce-app-ba189',
    storageBucket: 'ecommerce-app-ba189.appspot.com',
    iosClientId: '1062632767636-bsqmpq0mf2dobpquocbl5nft05jnq44o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVi9Ctv_tzmrcQLpF8arjMNTYxQOD6Vwk',
    appId: '1:1062632767636:ios:98880222830bcfd35db481',
    messagingSenderId: '1062632767636',
    projectId: 'ecommerce-app-ba189',
    storageBucket: 'ecommerce-app-ba189.appspot.com',
    iosClientId: '1062632767636-bsqmpq0mf2dobpquocbl5nft05jnq44o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
